spring.application.name=Delivery-Service
server.port=9020

ml-service.server.url=${ML_SERVICE_URL}

# Kafka Bootstrap
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY}' password='${KAFKA_API_SECRET}';
spring.kafka.properties.session.timeout.ms=45000
client.id=${KAFKA_CLIENT_ID}

# Schema Registry
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL}
spring.kafka.properties.basic.auth.credentials.source=USER_INFO
spring.kafka.properties.basic.auth.user.info=${SCHEMA_REGISTRY_API_KEY}:${SCHEMA_REGISTRY_API_SECRET}
spring.kafka.properties.auto.register.schemas=false
spring.kafka.properties.use.latest.version=true

# Consumer
spring.kafka.consumer.group-id=warehouse
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=false

# Kafka Topics
spring.kafka.topic.orders=ORDERS
spring.kafka.topic.orders.deliver=DELIVER_ORDERS

# Jackson
spring.jackson.mapper.accept_case_insensitive_properties=true

# Eureka
eureka.client.instance.preferIpAddress=false
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=${EUREKA_SERVER}/eureka/